const fs = require('fs');
let html = fs.readFileSync('life-planner.html', 'utf8');

// 1. Add menu card
const mmCard = `
        <div class="card-box" style="margin-bottom: 20px; cursor: pointer; border-right: 4px solid #8b5cf6;" onclick="startMemoryMatrixGame()">
          <h3 style="margin-bottom: 5px; color: var(--black);">مصفوفة الذاكرة 🧠</h3>
          <p style="font-size: 13px; color: var(--text2);">تذكر أماكن المربعات المضاءة بدقة وانقر عليها.</p>
        </div>
`;
html = html.replace(/(<div class="card-box"[^>]+onclick="startMemoryConnectGame\(\)"[\s\S]*?<\/div>\s*<\/div>\s*)/, '$1' + mmCard);

// 2. Add Game HTML Area
const mmArea = `
      <!-- Memory Matrix Game Area -->
      <div id="focus-mm-area" style="display: none; padding: 20px 0; text-align: center;">
        <h2 style="color: var(--primary); margin-bottom: 5px;">مصفوفة الذاكرة 🧠</h2>
        <p style="color: var(--text2); font-size: 14px; margin-bottom: 20px;">تذكر أماكن المربعات المضاءة وانقر عليها بعد اختفائها!</p>
        
        <div style="display: flex; justify-content: space-around; margin-bottom: 20px; font-weight: bold; background: var(--surface2); padding: 15px; border-radius: 16px;">
          <div>المرحلة: <span id="mm-level" style="color: var(--primary);">1</span>/15</div>
          <div>النقاط: <span id="mm-score" style="color: var(--primary);">0</span></div>
        </div>
        
        <div style="font-weight: bold; color: var(--text2); display:flex; align-items:center; justify-content:center; gap:8px; direction:ltr; margin-bottom:20px;">
          الوقت: <button class="circle-btn" onclick="adjustGameTime('mm', -10)" style="width:24px; height:24px; font-size:12px; padding:0; min-height:0; line-height:1; background:var(--surface2); color:var(--text); border:1px solid var(--border-darker); font-weight:bold;">-10</button> 
          <span id="mm-time" style="color:var(--black);">60</span> 
          <button class="circle-btn" onclick="adjustGameTime('mm', 10)" style="width:24px; height:24px; font-size:12px; padding:0; min-height:0; line-height:1; background:var(--surface2); color:var(--text); border:1px solid var(--border-darker); font-weight:bold;">+10</button>
        </div>
        
        <div id="mm-grid-container" style="display: flex; justify-content: center; margin-bottom: 20px; min-height: 300px; align-items: center;">
          <div id="mm-grid" style="display: grid; gap: 8px;">
            <!-- Grid generated by JS -->
          </div>
        </div>
        
        <button class="btn" style="background:var(--surface2); color:var(--text); margin-top:20px; width:100%; box-shadow:none;" onclick="quitFocusGame()">🔙 عودة للقائمة</button>
      </div>
`;
html = html.replace(/(<!-- Memory Connect Game Area -->[\s\S]*?<\/div>\s*<\/div>\s*)/, '$1' + mmArea);

// 3. Add to hide areas logic
html = html.replace(/(document\.getElementById\('focus-memory-area'\)\.style\.display = 'none';)/, "$1\n      document.getElementById('focus-mm-area').style.display = 'none';");

// 4. Add to adjustGameTime
html = html.replace(/else if \(game === 'dir'\)/, "else if (game === 'mm') { mmTimeLeft += amount; if(mmTimeLeft<0) mmTimeLeft=0; document.getElementById('mm-time').textContent = mmTimeLeft; }\n      else if (game === 'dir')");

// 5. Add Game JS Logic
const mmLogic = `
    // --- Memory Matrix Game ---
    let mmLevel = 1;
    let mmScore = 0;
    let mmTimeLeft = 60;
    let mmInterval;
    let mmSequence = [];
    let mmUserSequence = [];
    let mmGridSize = 3;
    let mmNumTargets = 3;
    let mmIsShowing = false;

    function startMemoryMatrixGame() {
      document.getElementById('focus-menu').style.display = 'none';
      document.getElementById('focus-direction-area').style.display = 'none';
      document.getElementById('focus-stroop-area').style.display = 'none';
      document.getElementById('focus-slide-area').style.display = 'none';
      document.getElementById('focus-wordsearch-area').style.display = 'none';
      document.getElementById('focus-infinity-area').style.display = 'none';
      document.getElementById('focus-memory-area').style.display = 'none';
      document.getElementById('focus-summatch-area').style.display = 'none';
      document.getElementById('focus-shapecounter-area').style.display = 'none';
      
      document.getElementById('focus-mm-area').style.display = 'block';
      
      mmLevel = 1; mmScore = 0; mmTimeLeft = 60;
      document.getElementById('mm-time').textContent = mmTimeLeft;
      if(mmInterval) clearInterval(mmInterval);
      
      isFocusGameActive = true;
      mmInterval = setInterval(() => {
        mmTimeLeft--;
        document.getElementById('mm-time').textContent = mmTimeLeft;
        if (mmTimeLeft <= 0) {
          clearInterval(mmInterval);
          isFocusGameActive = false;
          recordGameScore('mm', mmScore);
          alert(\`انتهى الوقت! نقاطك: \${mmScore}\`);
          startMemoryMatrixGame();
        }
      }, 1000);
      
      updateMMScoreboard();
      nextMMLevel();
    }

    function updateMMScoreboard() {
      document.getElementById('mm-level').textContent = mmLevel;
      document.getElementById('mm-score').textContent = mmScore;
    }

    function nextMMLevel() {
      if (mmLevel > 15) {
        clearInterval(mmInterval);
        isFocusGameActive = false;
        recordGameScore('mm', mmScore);
        alert(\`مبروك! لقد أنهيت جميع المراحل الـ 15! نقاطك النهائية: \${mmScore}\`);
        quitFocusGame();
        return;
      }
      
      if (mmLevel <= 3) { mmGridSize = 3; mmNumTargets = 3 + Math.floor((mmLevel-1)/2); }
      else if (mmLevel <= 6) { mmGridSize = 4; mmNumTargets = 4 + Math.floor((mmLevel-4)/2); }
      else if (mmLevel <= 9) { mmGridSize = 5; mmNumTargets = 5 + Math.floor((mmLevel-7)/2); }
      else if (mmLevel <= 12) { mmGridSize = 6; mmNumTargets = 6 + Math.floor((mmLevel-10)/2); }
      else { mmGridSize = 7; mmNumTargets = 7 + Math.floor((mmLevel-13)/2); }
      
      const gridEl = document.getElementById('mm-grid');
      gridEl.style.gridTemplateColumns = \`repeat(\${mmGridSize}, 1fr)\`;
      gridEl.innerHTML = '';
      
      const cellSize = Math.floor(280 / mmGridSize);
      
      const totalCells = mmGridSize * mmGridSize;
      const allIndices = Array.from({length: totalCells}, (_, i) => i);
      allIndices.sort(() => 0.5 - Math.random());
      mmSequence = allIndices.slice(0, mmNumTargets);
      mmUserSequence = [];
      mmIsShowing = true;
      
      for(let i = 0; i < totalCells; i++) {
        const cell = document.createElement('div');
        cell.className = 'mm-cell';
        cell.id = 'mm-cell-' + i;
        cell.style.width = \`\${cellSize}px\`;
        cell.style.height = \`\${cellSize}px\`;
        cell.style.backgroundColor = 'var(--surface2)';
        cell.style.borderRadius = '8px';
        cell.style.cursor = 'pointer';
        cell.style.transition = 'all 0.2s ease';
        cell.onclick = () => handleMMClick(i, cell);
        gridEl.appendChild(cell);
      }
      
      // Show pattern
      setTimeout(() => {
        mmSequence.forEach(idx => {
          const c = document.getElementById('mm-cell-' + idx);
          if (c) {
            c.style.backgroundColor = 'var(--primary)';
            c.style.transform = 'scale(1.05)';
            c.style.boxShadow = '0 0 10px var(--primary)';
          }
        });
        
        // Hide time decreases as level goes up (1500ms down to 600ms)
        const hideTime = Math.max(600, 1500 - (mmLevel * 60));
        
        setTimeout(() => {
          mmSequence.forEach(idx => {
            const c = document.getElementById('mm-cell-' + idx);
            if (c) {
              c.style.backgroundColor = 'var(--surface2)';
              c.style.transform = 'scale(1)';
              c.style.boxShadow = 'none';
            }
          });
          mmIsShowing = false;
        }, hideTime);
      }, 500);
    }

    function handleMMClick(idx, cellEl) {
      if (!isFocusGameActive || mmIsShowing) return;
      if (mmUserSequence.includes(idx)) return;
      
      cellEl.style.transform = 'scale(0.9)';
      setTimeout(() => { cellEl.style.transform = 'scale(1)'; }, 150);
      
      if (mmSequence.includes(idx)) {
        // Correct
        mmUserSequence.push(idx);
        cellEl.style.backgroundColor = 'var(--primary)';
        if(typeof playSound === 'function') playSound('soft');
        
        if (mmUserSequence.length === mmSequence.length) {
          mmScore += mmLevel * 10;
          mmLevel++;
          updateMMScoreboard();
          if(typeof playSound === 'function') playSound('achieve');
          setTimeout(() => { nextMMLevel(); }, 800);
        }
      } else {
        // Wrong
        cellEl.style.backgroundColor = '#ef4444'; // red
        if(typeof playSound === 'function') playSound('error'); 
        focusMistakes++; 
        document.getElementById('mistake-count').textContent = focusMistakes;
        
        // Show the rest of correct ones briefly
        mmSequence.forEach(i => {
          if (!mmUserSequence.includes(i)) {
            const c = document.getElementById('mm-cell-' + i);
            if(c) c.style.backgroundColor = '#f59e0b'; // orange to show missed
          }
        });
        
        mmIsShowing = true; // prevent further clicks
        setTimeout(() => { nextMMLevel(); }, 1500); // restart same level
      }
    }
`;
html = html.replace(/(function quitFocusGame\(\) {)/, mmLogic + '\n    $1');

// 6. Update Dashboard score logic
html = html.replace(/name: 'الذاكرة \(Memory\)', score: calcAvg\(\['mc'\]\)/, "name: 'الذاكرة (Memory)', score: calcAvg(['mc', 'mm'])");

fs.writeFileSync('life-planner.html', html);
console.log('Memory Matrix game added.');
